### ISSUE TITLE
Flashcard

### ISSUE THREAD

**Issue by AyushmanSoni** [opencodeiiita/Vision-1.0#107]
# Flashcard Prototyping
**OPEN TO ALL**
**No need to claim this issue** 
**NO SUBMISSION WILL BE ACCEPTED AFTER 23th December 11:59 P.M.**

*Hola Designers!*

In this task, you are supposed to create a Flashcard Prototype in Figma. What is a flip card?
Flip Cards is a flexible tool that allows you to solve a variety of marketing or educational tasks. Flip cards can be used for pros and cons, riddles and solutions, click to reveal, and much more. You can refer the following video for your reference:

- [Flashcard](https://youtu.be/arqZ8-4IM94?si=dnoYNmaWMVpqJaA-)
- [Flashcard](https://youtu.be/igQLml47YRY?si=_k16y1X_01_HmtQt)

## **Submission Guideline:**

- Submit the link of the Figma file in a .txt file under the "Flashcard" Folder only.

> This task is for 20 points. Again if PRs exceed the number 20 then first 10 contributors will get 10 points extra.

## **MDC (Minimum Design Criteria):**

Use images of your choice and show your creativity.

For any doubts related to the task or the submission process you can always ping us on discord. We will be happy to help.

**Comment by abhisheksharma010** [comment]
Claim

**Comment by kushal7201** [comment]
Claim
