### ISSUE TITLE
Copy Screen 02

### ISSUE THREAD

**Issue by AyushmanSoni** [opencodeiiita/Vision-1.0#113]
# Copy Screen 02
 **You need to claim this issue**
**THIS IS A FIRST COME FIRST SERVE ISSUE** 
**There will be a 24 hours deadline for each contributor who has been assigned the issue.**

_Hola Designers!_

In this task, you are supposed to create a copy design of given screen in Figma. Good UI of the app screens makes the app more visually appealing and bring friendly User Experience.

*Under first come first serve issue the issue will be assigned to one who has first asked for it.*
*If the contributor is failed to complete the task required in the given deadline of 24 hors so the other contributor will be assigned by this task after 24 hours.*

## Submission Guideline:

- Submit the link of the Figma file in a .txt file under the "Copy Screen 02" Folder only.
- In this figma file, the given screen and your designed one must be placed side by side, given one on the left and your designed one on the right.
- As most important point in this task is the accuracy you have achieved so try not to use any different colour or diiferent icon.
- Font named "Poppins" must be used only.

> This task is for **30 points**.

## MDC (Minimum Design Criteria):

-Since this task is for 30 points the design should be appropriate, consistent, and clean.

For any doubts related to the task or the submission process you can always ping us on discord. We will be happy to help.

## Screen to be copied:
![Screenshot (184)-01](https://github.com/opencodeiiita/Vision-1.0/assets/128999899/a91bd780-8d91-43fb-923f-246460b0cc3b)

**Comment by sarthakvermaa** [comment]
claim

**Comment by CodinJack** [comment]
claim

**Comment by kushal7201** [comment]
Claim

**Comment by chiragmalik2612** [comment]
cla

**Comment by ajay484** [comment]
claim

**Comment by Nandinig24** [comment]
Claims

**Comment by AyushmanSoni** [comment]
@sarthakvermaa you have been assigned to the task.

**Comment by sanju26honey** [comment]
Claim

**Comment by bhavyasri6475** [comment]
claim

**Comment by AyushmanSoni** [comment]
@sarthakvermaa are you doing the task ??
