### ISSUE TITLE
📌Liquid FAB✨

### ISSUE THREAD

**Issue by AyushmanSoni** [opencodeiiita/Vision-1.0#151]
# ✨Liquid FAB 💧
**OPEN TO ALL** 🌟🔓
**No need to claim this issue** 
**NO SUBMISSION WILL BE ACCEPTED AFTER 29th December 11:59 P.M.**

*Hola Design Dynamo!* 🌟
Welcome to a realm where pixels dance, colors sing, and creativity takes center stage! 🎨✨
In this task, you have to create a Liquid FAB in Figma.🚀✨
"A Liquid FAB (Floating Action Button) seamlessly integrates dynamic and smooth user interactions in a user interface."
👉 This is again an easy task of prototype for you all.  
👉 Do not copy the design shown in the video.
👉Show your creativity fill your button with design/image/icon of your choice.
👉I have also attached reference image and video.
👉You can refer the following video for your reference:

- Watch, and Dive 📺🔴 [Liquid FAB](https://youtu.be/KeH7GF38Kaw?si=FiR6eijGu5AOyATu)

## 📌 **Submission Guideline:**

- Submit the link of the Figma file in a .txt file under the "Liquid FAB" Folder only.

> This task is for 20 points. 2️⃣0️⃣✨
>Deadline is of 48 hours.🎉
Ready, set, DESIGN 🌟💻🚀

## 📌 **MDC (Minimum Design Criteria):**

At least 4 buttons must emerge out from the big one. there are 2 buttons shown in the video.
Use images/design in the button of your choice and show your creativity.
Do not fill just like it is shown in the video rather than you have to fill your button in some interesting way.

For any doubts related to the task or the submission process you can always ping us on discord. We will be happy to help.
![image](https://github.com/opencodeiiita/Vision-1.0/assets/128999899/e9166870-0d6a-41ff-8611-ff44168ec2a9)

**Comment by Apoorv012** [comment]
c
