### ISSUE TITLE
Liquid Switch

### ISSUE THREAD

**Issue by shashank-lol** [opencodeiiita/Vision-1.0#162]
# ✨Liquid Switch 💧
*OPEN TO ALL* 🌟🔓
*No need to claim this issue* 
*NO SUBMISSION WILL BE ACCEPTED AFTER 1st January 2:59 P.M.*

Hola Design Dynamos! 🌟
Welcome to a realm where pixels dance, colors sing, and creativity takes center stage! 🎨✨
In this task, you have to create a Liquid Switch in Figma.🚀✨
"A Liquid Switch seamlessly integrates dynamic and smooth user interactions of a button in a user interface." \
👉 This is again an easy task of prototype for you all. \
👉 Do not copy the design shown in the video. \
👉Show your creativity fill your button with design/image of your choice. \
👉I have also attached reference image and video. \
👉You can refer the following video for your reference:

- Watch, and Dive 📺🔴 [Liquid Switch](https://youtu.be/4iIaXZMc2BA?si=hCJr4QUBNVBOxNTA)
- [Reference 2](https://youtu.be/S6T6hrc8cQo?si=DMka8hSwZXy4vFXQ)

## 📌 *Submission Guideline:*

- Submit the link of the Figma file in a .txt file under the "Liquid Switch" Folder only.

> This task is for 20 points.✨ \
> Deadline is of 48 hours.🎉
Ready, set, DESIGN 🌟💻🚀

## 📌 *MDC (Minimum Design Criteria):*

Use images/design in the button of your choice and show your creativity.
Do not fill just like it is shown in the video rather than you have to fill your button in some interesting way.

For any doubts related to the task or the submission process you can always ping us on discord. We will be happy to help.

**Comment by kushal7201** [comment]
Claim

**Comment by Apoorv012** [comment]
c

**Comment by shashank-lol** [comment]
No need to claim. it is open for all
