### ISSUE TITLE
# 📌Copy Screen 04🎖️✨

### ISSUE THREAD

**Issue by AyushmanSoni** [opencodeiiita/Vision-1.0#199]
# 📌Copy Screen 04🎖️✨
  **👉You need to claim this issue**
**👉THIS IS A FIRST COME FIRST SERVE ISSUE** 
**👉There won't be any chance for correction, once you have submitted the task, points will be given according to your accuracy of design.**
**👉There will be a 24 hours deadline for each contributor who has been assigned the issue.**

_Hola, Design Dynamo! 🌟!_

🚀In this task, you are supposed to create a copy design of given screen in Figma. Good UI of the app screens makes the app more visually appealing and bring friendly User Experience.

*🚀Under first come first serve issue the issue will be assigned to one who has first asked for it.*
*🚀If the contributor is failed to complete the task required in the given deadline of 24 hours so the other contributor will be assigned by this task after 24 hours.*

## 📌Submission Guideline: (🔐📤 Seal the Deal)

- Submit the link of the Figma file in a .txt file under the "Copy Screen 04" Folder only.
- In this figma file, the given screen and your designed one must be placed side by side, given one on the left and your designed one on the right.
- As most important point in this task is the accuracy you have achieved so try not to use any different colour or diiferent icon.
- Font named "Poppins" must be used only.

> This task is for **30 points**.

## 📌MDC (Minimum Design Criteria):⚠️

-Since this task is for 30 points the design should be appropriate, consistent, and clean.

For any doubts related to the task or the submission process you can always ping us on discord. We will be happy to help.

## Screen to be copied:
![IMG_20240111_154034](https://github.com/opencodeiiita/Vision-1.0/assets/128999899/21a97aea-fd54-413e-995f-3e8393b8904f)

**Comment by sarthakvermaa** [comment]
claim

**Comment by AyushmanSoni** [comment]
> claim

assigned
