### ISSUE TITLE
Bottom Menu Animation

### ISSUE THREAD

**Issue by shashank-lol** [opencodeiiita/Vision-1.0#20]
# Bottom Menu Animation

**OPEN TO ALL** **No need to claim this issue** **NO SUBMISSION WILL BE ACCEPTED AFTER 15th December 11:59 P.M.**

_Hola Designers!_

In this task, you are supposed to create a Bottom Menu Animation in Figma. Good Animation in an app makes the UI appealing and improves the overall User Experience. You can refer the following video for your reference:
- [Bottom Menu Animation](https://www.youtube.com/watch?v=P8O78APM17c)

## Submission Guideline:

- Submit the link of the Figma file in a .txt file under the "Bottom Menu Animation" Folder only.

> This task is for **20 points**.

## MDC (Minimum Design Criteria):

The menu should look appealing and should not be exactly copied from the video. Also there should be atleast 4 icons in the menu and atmax 6.

For any doubts related to the task or the submission process you can always ping us on discord. We will be happy to help.

**Comment by kushal7201** [comment]
claim
