### ISSUE TITLE
Copy Screen 01

### ISSUE THREAD

**Issue by AyushmanSoni** [opencodeiiita/Vision-1.0#47]
# Copy Screen 01
 **You need to claim this issue**
**THIS IS A FIRST COME FIRST SERVE ISSUE** 
**There will be a 24 hours deadline for each contributor who has been assigned the issue.**

_Hola Designers!_

In this task, you are supposed to create a copy design of given screen in Figma. Good UI of the app screens makes the app more visually appealing and bring friendly User Experience.

*Under first come first serve issue the issue will be assigned to one who has first asked for it.*
*If the contributor is failed to complete the task required in the given deadline of 24 hors so the other contributor will be assigned by this task after 24 hours.*

## Submission Guideline:

- Submit the link of the Figma file in a .txt file under the "Copy Screen 01" Folder only.
- In this figma file, the given screen and your designed one must be placed side by side, given one on the left and your designed one on the right.
- As most important point in this task is the accuracy you have achieved so try not to use any different colour or diiferent icon.
- Font named "Poppins" must be used only.
- You have to use the provided images only.
- Remove the background of the bed and sofa images yourself.

> This task is for **30 points**.

## MDC (Minimum Design Criteria):

-Since this task is for 30 points the design should be appropriate, consistent, and clean.

For any doubts related to the task or the submission process you can always ping us on discord. We will be happy to help.

## Screen to be copied:
![copy screen-01 (1)](https://github.com/opencodeiiita/Vision-1.0/assets/128999899/06267925-6976-4a08-b6ff-2a325b5ff01a)
8
![sofa](https://github.com/opencodeiiita/Vision-1.0/assets/128999899/3cc3c4a2-d2a2-4b69-b769-69aafafd76b9)
![bed](https://github.com/opencodeiiita/Vision-1.0/assets/128999899/c258fc35-278d-4f71-b9ec-ff248c151220)
![basin](https://github.com/opencodeiiita/Vision-1.0/assets/128999899/e9d1ddbc-0883-40ad-8e96-f04970ad5c5b)
![chair](https://github.com/opencodeiiita/Vision-1.0/assets/128999899/45fda6c4-c6d4-4415-bfe2-adc56c5fd89d)

**Comment by CodinJack** [comment]
claim

**Comment by amankumar0724** [comment]
Claim

**Comment by nilesh9758** [comment]
Claim

**Comment by Talentedfalcon** [comment]
Claim

**Comment by ajay484** [comment]
Claim

**Comment by kushal7201** [comment]
Claim

**Comment by Jaysharma100** [comment]
Claim

**Comment by AyushmanSoni** [comment]
@CodinJack are you doing the task ??

**Comment by CodinJack** [comment]
@AyushmanSoni yea I am
will submit by evening

**Comment by ajay484** [comment]
claim
