### ISSUE TITLE
Apple's Dynamic Island

### ISSUE THREAD

**Issue by AyushmanSoni** [opencodeiiita/Vision-1.0#49]
# Apple's Dynamic Island

**OPEN TO ALL**
**No need to claim this issue**
**NO SUBMISSION WILL BE ACCEPTED AFTER 18th December 06:00 P.M.**

_Hola Designers!_

In this task, you are supposed to create an Animated dynamic island just same as present on iphones in Figma. Apple's dynamic island seamlessly blends innovation and user experience, creating a tech oasis that redefines the boundaries of possibility. You can refer the following video for your reference:
- [Apple's Dynamic Island](https://youtu.be/cl8m_mLKZ3I?si=feqkM7q2EuO3BmHF)

## Submission Guideline:

- Submit the link of the Figma file in a .txt file under the "Apple's Dynamic Island" Folder only.

> This task is for **20 points**.

## MDC (Minimum Design Criteria):

The Dynamic island must be properly animated and should not be exactly copied from the video. You have to use the colors of your choice and also song image of your choice. The animation of sound bars must be made up using at least 5 frames i.e., equal to or more than that is shown in the reference. Watch the reference video properly and show your creativity. The iphone shell is also provided in image format below, directly just right click and copy paste this image in figma file and create your dynamic island only on this screen.

For any doubts related to the task or the submission process you can always ping us on discord. We will be happy to help.

![image](https://github.com/opencodeiiita/Vision-1.0/assets/128999899/759a5801-6b10-4812-bd93-2857cedf7d42)

**Comment by kushal7201** [comment]
Claim

**Comment by AyushmanSoni** [comment]
no need to claim this issue , its open for all.
