### ISSUE TITLE
Image Carousel

### ISSUE THREAD

**Issue by AyushmanSoni** [opencodeiiita/Vision-1.0#67]
# Image Carousel Prototyping
**OPEN TO ALL**
**No need to claim this issue** 
**NO SUBMISSION WILL BE ACCEPTED AFTER 20th December 02:00 P.M.**

*Hola Designers!*

In this task, you are supposed to create a Image Carousel Prototype in Figma. Image carousels are interactive elements on web pages that showcase multiple images or content pieces in a rotating sequence. You can refer the following video for your reference:

- [Image Carousel](https://youtu.be/ZBKS7stXSio?si=mvQi0qiCDSQG7Xat)

## **Submission Guideline:**

- Submit the link of the Figma file in a .txt file under the "Image Carousel Prototyping" Folder only.

> This task is for 10 points.

## **MDC (Minimum Design Criteria):**

Use images of your choice and there should be at least 6 images.

For any doubts related to the task or the submission process you can always ping us on discord. We will be happy to help.

**Comment by kushal7201** [comment]
Claim

**Comment by kushal7201** [comment]
Claim
