### ISSUE TITLE
Glassmorphism with new scheme

### ISSUE THREAD

**Issue by AyushmanSoni** [opencodeiiita/Vision-1.0#89]
![IMG_20231221_131940](https://github.com/opencodeiiita/Vision-1.0/assets/128999899/4361478d-8fa7-44cc-a783-7a807ea22ab8)
# Glassmorphism login page

**OPEN TO ALL**
**No need to claim this issue**
**NO SUBMISSION WILL BE ACCEPTED AFTER 22th December 02:00 P.M.**

_Hola Designers!_

In this task, you have to create above shown glassmorphism effect in Figma. This is not an animation task. Glassmorphism effect adds sophisticated and contemporary feel to your app, making it stand out. You can refer the following video for your reference:
- [Glassmorphism effect](https://youtu.be/8UWkR1H5E4o?si=LpZ51xunuE_ZVHfy)

**Also there is one scheme in this task --> if Pull Requests for this task will exceed the number 20 then first 10 contributors will get 5 points as bonus. Plus if the number of pull requests will exceed 25 then first 15 contributors will get 5 points as bonus. So ask your friends to complete this task in more and more numbers. I will be bringing more such schemes in furthers tasks**
## Submission Guideline:

- Submit the link of the Figma file in a .txt file under the "Glassmorphism" Folder only.

> This task is for **20 points with the given scheme**.

## MDC (Minimum Design Criteria):

You have to create the above given glassmorphism effect login page with colors of your choice.
No need to create that like button shown in bottom right corner. Watch the reference video properly and show your creativity. Directly just right click and copy paste above given image in your figma file and create your effect.

For any doubts related to the task or the submission process you can always ping us on discord. We will be happy to help.

**Comment by Rohit-110** [comment]
claim

**Comment by abhisheksharma010** [comment]
claim

**Comment by abhisheksharma010** [comment]
I'm really interested in contributing to this issue and would love to get involved. Any chance you could assign the project to me? Thanks a bunch! 🌟

**Comment by kushal7201** [comment]
Claim
